export default class RouteKey {


    static SPLASH = "Splash"
    static LOGIN = "Login"
    static USER_WAITING = "USER_WAITING"
    static HOME = "Home"
    static USER_DASHBOARD = "USER_DASHBOARD"
    static DRAWER = "drawer"
    static REGISTER = "register"
    static FORGET_PASSWORD = "forgetPass"
    static CRM_CATEGORY = "Profiles"
    static CONTACT_US = "Contact Us"
    static ABOUT_US = "About Us"
    static QR_SCREEN = "QR Scan"
    static MAP = "MAP"
    static CHANGE_PORTAL_PASSWORD = "CHANGE_PORTAL_PASSWORD"
    static PORTAL_PASS_OTP = "PORTAL_PASS_OTP"
    static PORTAL_PASS_SUCCESS = "PORTAL_PASS_SUCCESS"

    static SURVEY_LIST = "Survey List"
    static PROFILE_DETAIL = "Profile Detail"
    static SURVEY_SELECTION = "Survey Selection"
    static FORM_BUILDING = "FORM_BUILDING"
    static GENERAL_SURVEY_LIST = "GENERAL_SURVEY_LIST"
    static PROFILE_SURVEY_LIST = "PROFILE_SURVEY_LIST"
    static PROFILE_FORMS = "PROFILE_FORMS"
    static DEFAULT_SURVEY_LIST = "DEFAULT_SURVEY_LIST"
    static PROFILE_UPDATION_LIST = "PROFILE_UPDATION_LIST"
    static PROFILE_UPDATE_REQUEST = "PROFILE_UPDATE_REQUEST"
    static PROFILE_REQUEST_TYPE = "PROFILE_REQUEST_TYPE"
    static PROFILE_REQUEST_SUB_TYPE = "PROFILE_REQUEST_SUB_TYPE"

    static PROFILE_COMPLAINT_TYPES = "PROFILE_COMPLAINT_TYPES"
    static PROFILE_COMPLAINT_SUB_TYPE = "PROFILE_COMPLAINT_SUB_TYPE"
    static PROFILE_COMPLAINT_REQUEST = "PROFILE_COMPLAINT_REQUEST"


    static ADD_NEW_PROFILE = "New Profile"
    static OTP = 'OTP'
    static REGION_LIST_SEARCH = "Region List"
    static CITY_LIST_SEARCH = "City List"
    static AREA_LIST_SEARCH = "Area List"
    static MARKET_LIST_SEARCH = "Market List"
    static CATEGORY_LIST_SEARCH = "Category List"
    static SUB_CATEGORY_SEARCH = "Sub-Category List"


    // runs and cash start
    static RUNS_ENCASHMENT = "Runs"
    static SEND_RUNS = "SEND_RUNS"
    static RUNS_SEARCH_TABS = "RUNS_SEARCH_TABS"
    static CASH_RETAILER_SEARCH_TABS = "CASH_RETAILER_SEARCH_TABS"

    // static SEARCH_BY_HISTORY_RUNS = "SEARCH_BY_HISTORY_RUNS"
    // static SEARCH_BY_CONTACT_RUNS = "SEARCH_BY_CONTACT_RUNS"
    // static SEARCH_BY_SCANQR_RUNS = "SEARCH_BY_SCANQR_RUNS"



    static CONFIRM_SEND_RUNS = "CONFIRM_SEND_RUNS"
    static SUCCESS_RUNS_SEND = "SUCCESS_RUNS_SEND"

    static CASH_DASHBOARD = 'CASH_DASHBOARD'
    static SEND_CASH = 'SEND_CASH'
    static CONFIRM_SEND_CASH = "CONFIRM_SEND_CASH"
    static SUCCESS_CASH_SEND = "SUCCESS_CASH_SEND"
    // runs and cash end



    // mechanic cash start
    static MECHANIC_CASH_DASHBOARD = "MECHANIC_CASH_DASHBOARD"
    static MECHANIC_SEND_CASH = "MECHANIC_SEND_CASH"
    static CONFIRM_MECHANIC_CASH = "CONFIRM_MECHANIC_CASH"
    static SUCCESS_MECHANIC_CASH = "SUCCESS_MECHANIC_CASH"
    static MECHANIC_SEARCH_TABS = "MECHANIC_SEARCH_TABS"

    // static CASH_DASHBOARD = 'CASH_DASHBOARD'
    // static SEND_CASH = 'SEND_CASH'
    // static CONFIRM_SEND_CASH = "CONFIRM_SEND_CASH"
    // static SUCCESS_CASH_SEND = "SUCCESS_CASH_SEND"

    // mechanic cash end




    static SEARCH_REGION_RUNS = "SearchRunsRegionList"
    static SEARCH_CITY_RUNS = "SearchRunsCityList"
    static SEARCH_AREA_RUNS = "SearchRunsAreaList"
    static SEARCH_MARKET_RUNS = "SearchRunsMarketList"
    static MECHANIC_LIST_RUNS = "mechanicListRuns"
    static RETAILER_LIST_RUNS = "retailerListRuns"






    static COMPLAINT_REQUEST_HOME = "COMPLAINT_REQUEST_HOME"
    static COMPLAINT_PRODUCT_LIST = "COMPLAINT_PRODUCT_LIST"
    static COMPLAINT_FORM = "COMPLAINT_FORM"
    static LODGE_COMPLAINT = "LODGE_COMPLAINT"
    static SUCCESS_COMPLAINT = "SUCCESS_COMPLAINT"
    static COMPLAINT_SOON = "COMPLAINT_SOON"
    static COMPLAINT_LIST = "COMPLAINT_LIST"
    static COMPLAINT_DETAIL = "COMPLAINT_DETAIL"
    static COMPLAINT_TYPE = "COMPLAINT_TYPE"
    static COMPLAINT_SUB_TYPE = "COMPLAINT_SUB_TYPE"




    static SEARCH_REGION_FILTER = "Search Region"
    static SEARCH_CITY_FILTER = "Search City"
    static SEARCH_AREA_FILTER = "Search Area"
    static SEARCH_MARKET_FILTER = "Search Market"
    static SEARCHED_PROFILES = "Profile Result"



    static SETTINGS_CONFIG = "SETTINGS_CONFIG"
    static LOCATION_SETTING_FILTER = "LOCATION_SETTING_FILTER"



    // new routing
    static REWARDS = "rewards"

    static USER_PROFILE = "USER_PROFILE"
    static ABOUT_APPLICATION = "ABOUT_APPLICATION"


    static SETTINGS = "SETTINGS"
    static IDENTITY_CHECK = "IDENTITY_CHECK"
    static SIGNUP_FORM = "SIGNUP_FORM"
    static SIGNUP_LOCATION = "SIGNUP_LOCATION"
    static REGION_SIGNUP = "REGION_SIGNUP"
    static CITY_SIGNUP = "CITY_SIGNUP"
    static AREA_SIGNUP = "AREA_SIGNUP"
    static MARKET_SIGNUP = "MARKET_SIGNUP"
    static CHOOSE_CATEGORY = "CHOOSE_CATEGORY"
    static LOGIN_OTP = "LOGIN_OTP"
    static GROUP_CATEGORY_SIGNUP = "GROUP_CATEGORY_SIGNUP"
    static CATEGORY_SIGNUP = "CATEGORY_SIGNUP"
    static SIGNUP_OTP = "SIGNUP_OTP"


    // ledger 
    static RUNS_LEDGER = "RUNS_LEDGER"
    static CASH_LEDGER = "CASH_LEDGER"
    static MECHANIC_CASH_LEDGER = "MECHANIC_CASH_LEDGER"
    static RUNS_LEDGER_CUSTOMER = "RUNS_LEDGER_CUSTOMER"
    static CASH_LEDGER_CUSTOMER = "CASH_LEDGER_CUSTOMER"
    static MECHANIC_CASH_LEDGER_CUSTOMER = "MECHANIC_CASH_LEDGER_CUSTOMER"


    static RUNS_CALCULATOR = "RUNS_CALCULATOR"
    static CP_PRICE_LIST = "CP_PRICE_LIST"
    static FIX_BRO_PROFILE = "FIX_BRO_PROFILE"
    static CONTACT_LIST = "CONTACT_LIST"
    static LAITH_MECHANIC_QR_SCAN = "LAITH_MECHANIC_QR_SCAN"
    static SCANABLE_ITEM_LIST = "SCANABLE_ITEM_LIST"


    static CLAIM_NAVIGATION = "CLAIM_NAVIGATION"
    static CLAIM_SOON = "CLAIM_SOON"
    static CLAIM_HOME = "CLAIM_HOME"
    static CLAIM_SCAN_PRODUCT = "CLAIM_SCAN_PRODUCT"

    static CLAIM_LIST = "CLAIM_LIST"
    static CLAIM_DETAIL = "CLAIM_DETAIL"

    static FIX_SOON = "FIX_SOON"


    static FIX_CATEGORY = "FIX_CATEGORY"
    static FIX_MAP_LOCATION = "FIX_MAP_LOCATION"
    static FIX_TYPES = "FIX_TYPES"
    static FIX_GROUPS = "FIX_GROUPS"


    // branding request start
    static BRANDING_REQUEST_HOME = "BRANDING_REQUEST_HOME"
    static BRAND_SOON = "BRAND_SOON"
    static BRANDING_REQUEST_FORM = "BRANDING_REQUEST_FORM"
    static BRAND_REQUEST_SUCCESS = "BRAND_REQUEST_SUCCESS"
    static FREE_GIFTS = "FREE_GIFTS"
    static BRANDING_NAVIGATION = "BRANDING_NAVIGATION"
    static BRANDING_REQUEST_LIST = "BRANDING_REQUEST_LIST"
    static BRANDING_REQUEST_DETAIL = "BRANDING_REQUEST_DETAIL"
    static BRANDING_STATUS_DETAIL = "BRANDING_STATUS_DETAIL"
    static BOARD_SHOP_REQUEST = "BOARD_SHOP_REQUEST"
    static BRANDING_WARNING = "BRANDING_WARNING"
    static BRANDING_SUCCESS = "BRANDING_SUCCESS"
    static SHUTTER_PAINT = "SHUTTER_PAINT"
    static COUNTER_PASTING_REQUEST = "COUNTER_PASTING_REQUEST"

    // branding request end

    static FREE_CASH = 'FREE_CASH'


    static ALERTS = "Alerts"
    static ALERT_HOME = "ALERT_HOME"
    static RETAILER_RUNS_ALERT_DETAIL = "RETAILER_RUNS_ALERT_DETAIL"

    static BRANDING_ALERT_LIST = "BRANDING_ALERT_LIST"
    static GENERAL_ALERT_LIST = "GENERAL_ALERT_LIST"
    static NEW_PROFILE_ALERT_LIST = "NEW_PROFILE_ALERT_LIST"
    static RUN_TRANSFER_ALERT_LIST = "RUN_TRANSFER_ALERT_LIST"

    static BRANDING_ALERT_DETAIL = "BRANDING_ALERT_DETAIL"
    static GENERAL_ALERT_DETAIL = "GENERAL_ALERT_DETAIL"
    static NEW_PROFILE_ALERT_DETAIL = "NEW_PROFILE_ALERT_DETAIL"
    static RUN_TRANSFER_ALERT_DETAIL = "RUN_TRANSFER_ALERT_DETAIL"


    static SCHEME_NAVIGATOR = "SCHEME_NAVIGATOR"
    static SCHEME_HOME = "SCHEME_HOME"




    // fix guru starting
    static FIX_GURU_NAVIGATION = "FIX_GURU_NAVIGATION"
    static FIX_GURU_HOME = "FIX_GURU_HOME"
    static FIX_GURU_SERVICE_LIST = "FIX_GURU_SERVICE_LIST"
    static FIX_GURU_CHOOSE_SERVICE = "FIX_GURU_CHOOSE_SERVICE"
    static ADD_FIX_GURU_SERVICE = "ADD_FIX_GURU_SERVICE"
    static FIX_GURU_TYPES_CHOOSE_SERVICE = "FIX_GURU_TYPES_CHOOSE_SERVICE"
    static FIX_GURU_TYPES_MODELS = "FIX_GURU_TYPES_MODELS"
    // fix guru ending



    static SPIN_AND_WIN_HOME = "SPIN_AND_WIN_HOME"
    static SCHEME_MENU = "SCHEME_MENU"


    static ORDER_HOME = "ORDER_HOME"
    static NEW_ORDER_HOME = "NEW_ORDER_HOME"
    static NEW_ORDER_ITEM_LIST = "NEW_ORDER_ITEM_LIST"
    static NEW_ORDER_CONFIRM = "NEW_ORDER_CONFIRM"

    static ORDER_SUCCESS = "ORDER_SUCCESS"
    static ORDER_HISTORY_HOME = "ORDER_HISTORY_HOME"
    static VIEW_HISTORY_ORDER = "VIEW_HISTORY_ORDER"
    static CHECK_HISTORY_ORDER_OFFER = "CHECK_HISTORY_ORDER_OFFER"
    static HISTORY_CONFIRM_ORDER = "HISTORY_CONFIRM_ORDER"
    static HISTORY_VIEW_VARIETY = "HISTORY_VIEW_VARIETY"
    static HISTORY_ACCEPTED_OFFER = "HISTORY_ACCEPTED_OFFER"
    static RECEIVED_ORDERS_LIST = "RECEIVED_ORDERS_LIST"
    static RECEIVED_ORDER_VIEW = "RECEIVED_ORDER_VIEW"
    static CONFIRM_RECEIVED_ORDER = "CONFIRM_RECEIVED_ORDER"
    static SUCCESS_RECEIVED_ORDER = "SUCCESS_RECEIVED_ORDER"
    static OFFER_HISTORY_HOME = "OFFER_HISTORY_HOME"
    static OFFER_DETAIL = "OFFER_DETAIL"

    // 
    static NEW_SCHEME = "NEW_SCHEME"
    static REVIEW_SCHEME = "REVIEW_SCHEME"
    static SCHEME_BUYING_SOURCES = "SCHEME_BUYING_SOURCES"
    static NEW_SCHEME_CONFIRM = "NEW_SCHEME_CONFIRM"
    static NEW_SCHEME_SUCCESS = "NEW_SCHEME_SUCCESS"
    static EASY_LOAD_HOME = "EASY_LOAD_HOME"
    static EASY_LOAD_HISTORY = "EASY_LOAD_HISTORY"
    static NEW_EASY_LOAD = "NEW_EASY_LOAD"
    static EASY_LOAD_CONFIRM = "EASY_LOAD_CONFIRM"
    static EASY_LOAD_SUCCESS = "EASY_LOAD_SUCCESS"
    static SCHEME_HISTORY_HOME = "SCHEME_HISTORY_HOME"
    static SCHEME_HISTORY_VIEW_ORDER = "SCHEME_HISTORY_VIEW_ORDER"

    static SCHEME_PENDING_ORDER_HOME = "SCHEME_PENDING_ORDER_HOME"
    static SCHEME_PENDING_ORDER_DETAIL = "SCHEME_PENDING_ORDER_DETAIL"
    static SCHEME_PENDING_ORDER_CONFIRM = "SCHEME_PENDING_ORDER_CONFIRM"
    static SCHEME_PENDING_ORDER_SUCCESS = "SCHEME_PENDING_ORDER_SUCCESS"
    static SCHEME_APPROVAL_HISTORY_HOME = "SCHEME_APPROVAL_HISTORY_HOME"
    static SCHEME_APPROVAL_CUSTOMER_WISE = "SCHEME_APPROVAL_CUSTOMER_WISE"
    static SCHEME_HISTORY_CUSTOMER_WISE = "SCHEME_HISTORY_CUSTOMER_WISE"
    static SCHEME_APPROVAL_HISTORY_DETAIL = "SCHEME_APPROVAL_HISTORY_DETAIL"

    static DELIVERY_FORM = "DELIVERY_FORM"
    static DELIVERY_SUCCESS = "DELIVERY_SUCCESS"
    static VIEW_DELIVERY_DETAIL = "VIEW_DELIVERY_DETAIL"
    // 
    static BUNDLE_BUYING_SOURCE = "BUNDLE_BUYING_SOURCE"
    static BUNDLE_SCHEMES = "BUNDLE_SCHEMES"
    static VIEW_BUNDLES = "VIEW_BUNDLES"
    static CONFIRM_BUNDLES = "CONFIRM_BUNDLES"
    static BUNDLE_SUCCESS = "BUNDLE_SUCCESS"
    static BUNDLE_SCHEME_HISTORY_LIST = "BUNDLE_SCHEME_HISTORY_LIST"
    static BUNDLE_SCHEME_HISTORY_DETAIL = "BUNDLE_SCHEME_HISTORY_DETAIL"
    static RECEIVE_BUNDLE_LIST = "RECEIVE_BUNDLE_LIST"
    static RECEIVE_BUNDLE_DETAIL = "RECEIVE_BUNDLE_DETAIL"
    static RECEIVE_BUNDLE_CONFIRM = "RECEIVE_BUNDLE_CONFIRM"
    static RECEIVE_BUNDLE_SUCCESS = "RECEIVE_BUNDLE_SUCCESS"
    static BUNDLE_SELLER_HISTORY_LIST = "BUNDLE_SELLER_HISTORY_LIST"
    static BUNDLE_SELLER_HISTORY_DETAIL = "BUNDLE_SELLER_HISTORY_DETAIL"
    static BUNDLE_SCHEME_HISTORY_CUSTOMER_WISE = "BUNDLE_SCHEME_HISTORY_CUSTOMER_WISE"
    static BUNDLE_SELLER_CUSTOMER_WISE = "BUNDLE_SELLER_CUSTOMER_WISE"

    static BUNDLE_DELIVERY_FORM = "BUNDLE_DELIVERY_FORM"
    static BUNDLE_DELIVERY_SUCCESS = "BUNDLE_DELIVERY_SUCCESS"
    static BUNDLE_DELIVERY_DETAIL = "BUNDLE_DELIVERY_DETAIL"

}