
const ColorsApp = {

    // backend url
    PRIMARY: "#ff8400",
    SECOND: "#fb3d3c",
    RETAILER_PRIMARY: "#158CBA",
    RETAILER_SECOND: "#157EE6",
    BACK_COLOR: "lightgray",



    // theme
    GRAY_TEXT: '#707070',
    SEA_GREEN: '#00C770',
    ORANGE_THEME_COLOR: '#FF7700',
    PEACH_COLOR: '#FF5A5A',
    BLACK_THEME_COLOR: '#3F3D56',
    RED_THEME_COLOR: '#FF3D00',
    RED_LOGIN_COLOR: '#ED1C24',

    DARK_PINK_THEME_COLOR: '#B22020',
    LIGHT_PINK_THEME_COLOR: '#FFACAC',
    LIGHT_GREEN_THEME: '#9EFFA4',
    DARK_GREEN_THEME: '#0F8A16',
    LIGHT_GREEN_BOX_THEME: '#37D38E',

    LIGHT_BLUE_THEME: '#D1D9FF',
    LIGHT_BOX_BLUE_THEME: '#A1B1FF',
    DARK_BLUE_THEME: '#3F4C8E',


    LIGHT_VIOLET_THEME: '#EBD4FF',
    LIGHT_BOX_VIOLET_THEME: '#D3A1FF',
    DARK_VIOLET_THEME: '#7A559B',


    LIGHT_BROWN_FIX: '#FF8F65',
    DARK_BROWN_FIX: '#6B3520',
    BROWN_TEXT_COLOR: '#AB0404',
    CREAM_COLOR: '#FCCCBA',


    LIGHT_SKY_GREEN: '#c8edde',
    DARK_SKY_GREEN: '#a8e6cf',
    DARK_SKY_GREEN_THEME: '#065b34',

    LIGHT_REGISTER_PINKISH: '#FEE3E4',
    CREAM_QR_BOX: '#FFD3B6',

    BLUE_FREE_THEME_LIGHT: "#4dd7fa",
    BLUE_FREE_THEME_DARK: "#0e6f8c",

    RED_FREE_THEME_LIGHT: "#d40019",



    // notification 

    BRAND_NOTIFICATION: "#c8edde",
    COMPLAINT_NOTIFICATION: "#EBD4FF",
    NEW_PROFILE_NOTIFICATION: "#fffd7e",
    RUNS_TRANSFER_NOTIFICATION: "#FFACAC",
    GENERAL_NOTIFICATION: "#4DDBFB",

    ROCKET_BLUE: "#0A1B61",
    ROCKET_RED: "#FF4141",
    ROCKET_GREEN: "#37CC68",
    ROCKET_FUCHSIA: "#EA3453",
    ROCKET_GRAY_BG: '#d6d6d6',
    ROCKET_YELLOW: '#fbff10',

    FIX_GURU_THEME_COLOR: "#0088FF",

    FIX_CREAM_BACKGROUND_COLOR: "#FFFFF0",



    LEMON_BG_COLOR: "#FFF3DE",
    LEMON_BUTTON_COLOR: "#FF9500",
    DARK_LEMON_TEXT_COLOR: "#5C3600",
    LIGHT_LEMON_COLOR: "#FFFADF",
    LIGHT_PINK_COLOR: "#FFEBEB",
    DARK_PINK_COLOR: "#550500",



    PROCEED_BUTTON_BACKGROUND: "#C5FFE4",
    PROCEED_BUTTON_TEXT: "#077441",


    LIGHT_BLACK: "#4B4949",
    BROWN_ICONS_COLOR: "#AC4D4D",
    SELCTED_CHIP_ORANGE_COLOR: "#FFECDC",

    LIGHT_BROWN_COLOR: "#FFD4AE",
    DARK_BROWN_COLOR: "#7E1A00",

    BUTTON_LIGHT_GREEN_BG: "#AEFFC6",
    BUTTON_DARK_GREEN_TEXT: "#09611F",
    DISABLED_COLOR: "#A8A8A8",


    SQUARE_BOX_YELLOW_COLOR: "#FFF6A2",

    SCHEME_BOX_YELLOW_LIGHT: "#FFF0B7",
    SCHEME_BOX_SEA_GREEN_LIGHT: "#CBFFD8",
    LIGHT_GRAY_BG_COLOR: "#E5E5E5",


    LIGHT_BLUE_BG_COLOR: "#B7DAFF",
    DARK_BLUE_TEXT_COLOR: "#002C5C",


    SCHEME_RED_COLOR: "#FF3B30",
    EASYLOAD_GREEN_COLOR: "#34C759",
    GRAY_100: "#3B3B41",


    DARK_MEGENTA_COLOR: "#BB0C2E",
    WALLET_LIGHT_GREEN_COLOR: "#CBFFD8",
    INDIGO_LIGHT_COLOR: "#F1F1FF",
    INDIGO_DARK_COLOR: "#5856D6",

    LIGHT_TEAL_COLOR: "#EEFAFF",
    DARK_TEAL_COLOR: "#44AAD8",


    LIGHT_MEGENTA_COLOR: "#FFEAEE",

    FIX_GURU_DASH_LIGH: "#E5F1FF",
    OFF_WHITE_COLOR: "#FFF4E5",
    LIGHT_ORANGE_BOX_COLOR: "#FFE1B7",
    LIME_GREEN_COLOR: "#CBFFD8",

    LIGHT_SCHEME_MENU_CREAM_1: "#FFCE8A",
    DARK_SCHEME_MENU_CREAM_1: "#5C3600",

    LIGHT_SCHEME_MENU_CREAM_2: "#FFE1B7",
    DARK_SCHEME_MENU_CREAM_2: "#854E00",

    LIGHT_SCHEME_MENU_CREAM_3: "#FFF4E5",
    DARK_SCHEME_MENU_CREAM_3: "#AD6500",

    DARK_GRAY_ON_GRAY: "#4F4F56",
    BLUE_BORDERED_COLOR: "#0067D6",
    LIGHT_BLUE_SHOP_COLOR: "#CAEEFF",
    GRAY_BACKGROUND:"#F9F9F9",

    LEDGER_CASH_BUTTON_BG:"#EFFFF3",
    LEDGER_CASH_BUTTON_TEXT:"#22A543",

}

export default ColorsApp;
